services:
  port-helper:
    image: strenkml/qbittorrent-porthelper
    build:
      context: .
    restart: unless-stopped
    container_name: qbittorrent-porthelper
    environment:
      - QBITTORRENT_HOST=127.0.0.1
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
      - QBITTORRENT_UPDATE_TIME_SECONDS=60
      - PIA_PORT_FILE_NAME=port.txt
    volumes:
      - /PATH/TO/DIR/CONTAINING/PORT/FILE:/pia_port
